import services.CandidateService

def candidateService = new CandidateService()

def jedis = candidateService.connectToRedis()
def candidates = [
        '{"id":"1", "firstName":"John", "lastName":"Smith"}',
        '{"id":"2", "firstName":"Deanna", "lastName":"Morgan"}',
        '{"id":"3", "firstName":"Daniel", "lastName":"Lloyd"}',
        '{"id":"4", "firstName":"Daryl", "lastName":"Richards"}',
        '{"id":"5", "firstName":"Kellan", "lastName":"Jones"}',
        '{"id":"6", "firstName":"Alexia", "lastName":"Mason"}',
        '{"id":"7", "firstName":"Sam", "lastName":"Brooks"}',
        '{"id":"8", "firstName":"Clark", "lastName":"Grant"}',
        '{"id":"9", "firstName":"Paige", "lastName":"Stevens"}',
        '{"id":"10", "firstName":"Thomas", "lastName":"Moore"}',
        '{"id":"11", "firstName":"Darcy", "lastName":"Robinson"}',
        '{"id":"12", "firstName":"Hailey", "lastName":"Riley"}',
        '{"id":"13", "firstName":"Sawyer", "lastName":"Smith"}',
        '{"id":"14", "firstName":"Valeria", "lastName":"Dixon"}',
        '{"id":"15", "firstName":"Savana", "lastName":"Baker"}',
        '{"id":"16", "firstName":"Melanie", "lastName":"Baker"}',
        '{"id":"17", "firstName":"Maximilian", "lastName":"Parker"}',
        '{"id":"18", "firstName":"Spike", "lastName":"Craig"}',
        '{"id":"19", "firstName":"Valeria", "lastName":"Johnston"}',
        '{"id":"20", "firstName":"Sophia", "lastName":"Farrell"}',
        '{"id":"21", "firstName":"Adison", "lastName":"Morris"}',
        '{"id":"22", "firstName":"Ryan", "lastName":"Harper"}',
        '{"id":"23", "firstName":"Isabella", "lastName":"Robinson"}',
        '{"id":"24", "firstName":"Tara", "lastName":"Barnes"}',
        '{"id":"25", "firstName":"Myra", "lastName":"Payne"}',
        '{"id":"26", "firstName":"Florrie", "lastName":"Perkins"}',
        '{"id":"27", "firstName":"Ellia", "lastName":"Owens"}',
        '{"id":"28", "firstName":"Daniel", "lastName":"Payne"}',
        '{"id":"29", "firstName":"Leonardo", "lastName":"Russell"}',
        '{"id":"30", "firstName":"Mary", "lastName":"Jones"}',
        '{"id":"31", "firstName":"Florrie", "lastName":"Ellis"}',
        '{"id":"32", "firstName":"Adison", "lastName":"Roberts"}',
        '{"id":"33", "firstName":"Miley", "lastName":"Henderson"}',
        '{"id":"34", "firstName":"Carlos", "lastName":"Nelson"}',
        '{"id":"35", "firstName":"Emma", "lastName":"Turner"}',
        '{"id":"36", "firstName":"Annabella", "lastName":"Moore"}',
        '{"id":"37", "firstName":"Frederick", "lastName":"Perkins"}',
        '{"id":"38", "firstName":"Julia", "lastName":"Edwards"}',
        '{"id":"39", "firstName":"Adam", "lastName":"Turner"}',
        '{"id":"40", "firstName":"Mary", "lastName":"Spencer"}',
        '{"id":"41", "firstName":"Lily", "lastName":"Alexander"}',
        '{"id":"42", "firstName":"Julia", "lastName":"Alexander"}',
        '{"id":"43", "firstName":"Savana", "lastName":"Hill"}',
        '{"id":"44", "firstName":"Michael", "lastName":"Riley"}',
        '{"id":"45", "firstName":"Martin", "lastName":"Richardson"}',
        '{"id":"46", "firstName":"Vincent", "lastName":"Wells"}',
        '{"id":"47", "firstName":"Daniel", "lastName":"Harrison"}',
        '{"id":"48", "firstName":"Freddie", "lastName":"Williams"}',
        '{"id":"49", "firstName":"Alford", "lastName":"Moore"}',
        '{"id":"50", "firstName":"Frederick", "lastName":"Howard"}',
        '{"id":"51", "firstName":"James", "lastName":"Spencer"}',
        '{"id":"52", "firstName":"Byron", "lastName":"Riley"}',
        '{"id":"53", "firstName":"Alberta", "lastName":"Taylor"}',
        '{"id":"54", "firstName":"Victor", "lastName":"Martin"}',
        '{"id":"55", "firstName":"Paige", "lastName":"Howard"}',
        '{"id":"56", "firstName":"Nicole", "lastName":"Edwards"}',
        '{"id":"57", "firstName":"Daisy", "lastName":"Stewart"}',
        '{"id":"58", "firstName":"Vincent", "lastName":"Cunningham"}',
        '{"id":"59", "firstName":"Jasmine", "lastName":"Richards"}',
        '{"id":"60", "firstName":"Charlie", "lastName":"Hunt"}',
        '{"id":"61", "firstName":"Brad", "lastName":"Johnston"}',
        '{"id":"62", "firstName":"Sophia", "lastName":"Fowler"}',
        '{"id":"63", "firstName":"Alisa", "lastName":"Armstrong"}',
        '{"id":"64", "firstName":"Emma", "lastName":"Hill"}',
        '{"id":"65", "firstName":"Violet", "lastName":"Craig"}',
        '{"id":"66", "firstName":"Amanda", "lastName":"Robinson"}',
        '{"id":"67", "firstName":"Rebecca", "lastName":"Fowler"}',
        '{"id":"68", "firstName":"Sydney", "lastName":"Johnson"}',
        '{"id":"69", "firstName":"Oliver", "lastName":"Holmes"}',
        '{"id":"70", "firstName":"Arthur", "lastName":"Kelly"}',
        '{"id":"71", "firstName":"Rebecca", "lastName":"Chapman"}',
        '{"id":"72", "firstName":"David", "lastName":"Ferguson"}',
        '{"id":"73", "firstName":"Jared", "lastName":"Gibson"}',
        '{"id":"74", "firstName":"Camila", "lastName":"West"}',
        '{"id":"75", "firstName":"Tess", "lastName":"Owens"}',
        '{"id":"76", "firstName":"Sydney", "lastName":"Foster"}',
        '{"id":"77", "firstName":"Chester", "lastName":"Hill"}',
        '{"id":"78", "firstName":"Julia", "lastName":"Myers"}',
        '{"id":"79", "firstName":"Mary", "lastName":"Kelly"}',
        '{"id":"80", "firstName":"Garry", "lastName":"Stewart"}',
        '{"id":"81", "firstName":"Naomi", "lastName":"Edwards"}',
        '{"id":"82", "firstName":"Jordan", "lastName":"Perry"}',
        '{"id":"83", "firstName":"Dominik", "lastName":"Alexander"}',
        '{"id":"84", "firstName":"Eleanor", "lastName":"Kelley"}',
        '{"id":"85", "firstName":"Daryl", "lastName":"Mitchell"}',
        '{"id":"86", "firstName":"Hailey", "lastName":"Payne"}',
        '{"id":"87", "firstName":"Kellan", "lastName":"Foster"}',
        '{"id":"88", "firstName":"Belinda", "lastName":"Richards"}',
        '{"id":"89", "firstName":"Kirsten", "lastName":"Johnson"}',
        '{"id":"90", "firstName":"Evelyn", "lastName":"Miller"}',
        '{"id":"91", "firstName":"Mary", "lastName":"Alexander"}',
        '{"id":"92", "firstName":"Adison", "lastName":"Morrison"}',
        '{"id":"93", "firstName":"Daryl", "lastName":"Johnston"}',
        '{"id":"94", "firstName":"Connie", "lastName":"Harper"}',
        '{"id":"95", "firstName":"Ashton", "lastName":"Ryan"}',
        '{"id":"96", "firstName":"Maximilian", "lastName":"Walker"}',
        '{"id":"97", "firstName":"Sienna", "lastName":"Ryan"}',
        '{"id":"98", "firstName":"Antony", "lastName":"Edwards"}',
        '{"id":"99", "firstName":"Alexia", "lastName":"Armstrong"}',
        '{"id":"100", "firstName":"Natalie", "lastName":"Clark"}'
]
for(candidate in candidates){
    candidateService.setActiveCandidate(jedis, "candidateStream", candidate)
}

println("Finished")



